### ISSUE TITLE
SafeAuth wallet fails to connect to any dapp due to websocket connection error (Project ID is missing) (safe.web3auth.com)

### ISSUE THREAD

**Issue by MrKampla** [Web3Auth/web3auth-web#1658]
### SafeAuth wallet fails to connect to any dapp due to websocket connection error
When trying to connect safeAuth wallet (safe.web3auth.com) with any dapp, nothing happens in the UI, but there's an error thrown in the console:

{context:'core'} {context:'core/relayer'} Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: Project ID is missing)

### **To Reproduce**

1. Go to https://safe.web3auth.com/
2. login with google
3. click on wallet connect icon
4. Paste WalletConnect QR Link obtained from a dapp (I was trying with beefy finance https://app.beefy.com/)
5. nothing happens, the error is thrown in the console

### **Expected behavior**

Wallet connects with the website successfully.

### **Screenshots**

![image](https://github.com/Web3Auth/web3auth-web/assets/46401284/a0ec5a89-0a14-4045-b89c-82f30511a2ca)

### **Device Info:**

- Device: MacBook Pro
- OS: macOS 14
- Browser chrome
- Version 119
- Web3Auth Version: ?

**Comment by chaitanyapotti** [comment]
This is fixed in the latest version

**Comment by MrKampla** [comment]
The issue still persists on my machine. Has the fixed version already been deployed?
