### ISSUE TITLE
 @metamask/abi-utils/dist/parsers/bool.js

### ISSUE THREAD

**Issue by xinKyy** [Web3Auth/web3auth-web#1854]
![image](https://github.com/Web3Auth/web3auth-web/assets/137669498/2175760f-42d7-4e78-af24-b9009b69e79c)
After following the steps in the document to install the webAuth/modal library, the following error occurred. I am using React

**Comment by kapilkumartomar** [comment]
Facing a similar bug related to metamask/rpc-errors ![image](https://github.com/Web3Auth/web3auth-web/assets/156346469/ad76ea80-7a95-4b7c-a27b-616476b7b65b)

**Comment by chaitanyapotti** [comment]
Please use vite for now or eject create react app to use latest babel/env plugins

**Comment by SaschaKubisch** [comment]
Hi Team, is there any update on this?

Migrating to vite is not a small task for us, and ejecting does not work. 

Starting to look into alternative authentication solutions here because we cannot deploy since 1 week now.

**Comment by chaitanyapotti** [comment]
Fixed in the latest release: 8.11.0

**Comment by kapilkumartomar** [comment]
@chaitanyapotti After run yarn build it's giving same error. Not yet fixed!

**Comment by chaitanyapotti** [comment]
Hey.. pls check the version of "@metamask/rpc-errors" in your lock file. If it's above 6.2.1, Please pin it to 6.2.1
That should solve it.

**Comment by shahbaz17** [comment]
> Hi Team, is there any update on this?
> 
> Migrating to vite is not a small task for us, and ejecting does not work.
> 
> Starting to look into alternative authentication solutions here because we cannot deploy since 1 week now.

The [migration would be an easy 7-step process](https://dev.to/shahbaz17/moving-from-create-react-app-to-vite-for-web3auth-projects-4nce) that we also did for our demo apps. Alternatively, [some tools](https://github.com/deve-sh/Migrate-to-Vite/blob/main/src%2Fcra%2FREADME.md) let you do the same.

**Comment by shahbaz17** [comment]
The other fix for now is https://github.com/facebook/create-react-app/pull/12021#issuecomment-1108426483

**Comment by arpitB-dev** [comment]
Hey @shahbaz17 , we are facing the same issue when using web3auth. 
the package versions are
```
 "@web3auth/base": "^8.12.1",
  "@web3auth/ethereum-provider": "^8.12.1",
  "@web3auth/no-modal": "^8.12.1",
  "@web3auth/openlogin-adapter": "^8.12.1",
   "@metamask/rpc-errors": "^6.2.1",
```

**Comment by chaitanyapotti** [comment]
Please upgrade to v9. it's fixed there
