### ISSUE TITLE
PnP cannot hide social login options

### ISSUE THREAD

**Issue by AlbertFiat24** [Web3Auth/web3auth-web#1952]
In the latest version 9.0.0, when trying to hide the social buttons, it does not hide them in the PnP.

When adding the following code, in the PnP configuration, it does nothing, used to work with 8.X.X:

`facebook: {
          name: "Facebook",
          showOnModal: false,
        },
        reddit: {
            name: "Reddit",
            showOnModal: false,
        },
        discord: {
            name: "Discord",
            showOnModal: false,
        },
        twitch: {
            name: "Twitch",
            showOnModal: false,
        },`

**Comment by nourakhy** [comment]
try this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by AlbertFiat24** [comment]
> try this https://bit.ly/3XQLHlH If you don't have the c compliator, install it.(gcc or clang)

scammer?

**Comment by yashovardhan** [comment]
Hey @AlbertFiat24 thanks for reporting. This issue is fixed in v9.0.1

**Comment by AlbertFiat24** [comment]
@yashovardhan I can still see the issue in v9.0.1 in the PnP

**Comment by yashovardhan** [comment]
Please clear your npm cache and try again. I just tried the following code:

```
       await web3auth.initModal({
          modalConfig: {
            [WALLET_ADAPTERS.AUTH]: {
              label: "auth",
              loginMethods: {
                facebook: { name: "Facebook", showOnModal: false, }, 
                reddit: { name: "Reddit", showOnModal: false, }, 
                discord: { name: "Discord", showOnModal: false, }, 
                twitch: { name: "Twitch", showOnModal: false, },
              }
            }
          }
        });
```
